version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  vgstandard-data-importer:
    build:
      context: .
      dockerfile: VGStandard.Data.Importer/Dockerfile
      args:
       - BUILD_CONFIGURATION=Release
    depends_on:
      - elasticsearch
      - postgres
    command: ["--bulk-postgres", "--bulk-elasticsearch"]

  vgstandard-webapi:
    build:
      context: .
      dockerfile: VGStandard.WebAPI/Dockerfile
      args:
        - BUILD_CONFIGURATION=Release
    ports:
      - "5001:80"
    depends_on:
      - elasticsearch
      - postgres
      - vgstandard-data-importer
