name: Docker Build and Push

on:
  push:
    branches: [ master ]

jobs:
  build-and-push-data-importer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push VGStandard.Data.Importer
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./VGStandard.Data.Importer/Dockerfile
        push: true
        tags: dakotairsik/vgstandard-data-importer:latest
    - name: Zip VGStandard.Data.Importer
      run: zip -r vgstandard-data-importer-bin.zip ./VGStandard.Data.Importer
    - name: Upload VGStandard.Data.Importer Binaries
      uses: actions/upload-artifact@v2
      with:
        name: vgstandard-data-importer
        path: vgstandard-data-importer-bin.zip
