name: Docker Build and Push

on:
  push:
    branches: [ master ]

jobs:
  build-and-push-data-importer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'  # Specify your .NET version

    - name: Restore dependencies
      run: dotnet restore "./VGStandard.Data.Importer/VGStandard.Data.Importer.csproj"

    - name: Publish
      run: dotnet publish "./VGStandard.Data.Importer/VGStandard.Data.Importer.csproj" -c Release -o ./app

    - name: Zip VGStandard.Data.Importer
      run: zip -r vgstandard-data-importer-bin.zip ./app

    - name: Set Release Tag Name
      run: echo "RELEASE_TAG=$(echo master-$(date +'%m-%d-%Y-%H-%M-%S'))" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false

    - name: Upload VGStandard.Data.Importer Binary as Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vgstandard-data-importer-bin.zip
        asset_name: vgstandard-data-importer-bin.zip
        asset_content_type: application/zip
        
    - name: Restore dependencies for VGStandard.WebAPI
      run: dotnet restore "./VGStandard.WebAPI/VGStandard.WebAPI.csproj"

    - name: Publish VGStandard.WebAPI
      run: dotnet publish "./VGStandard.WebAPI/VGStandard.WebAPI.csproj" -c Release -o ./webapi-app

    - name: Zip VGStandard.WebAPI
      run: zip -r vgstandard-webapi-bin.zip ./webapi-app

    - name: Upload VGStandard.WebAPI Binary as Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vgstandard-webapi-bin.zip
        asset_name: vgstandard-webapi-bin.zip
        asset_content_type: application/zip    
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./VGStandard.Data.Importer/Dockerfile
        push: true
        tags: dakotairsik/vgstandard-data-importer:latest
        
    - name: Build and push VGStandard.WebAPI Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./VGStandard.WebAPI/Dockerfile
        push: true
        tags: dakotairsik/vgstandard-webapi:latest


